### ISSUE TITLE
Protocol Specification Document

### ISSUE THREAD

**Issue by Alkass** [dimitrievski/ruptela#2]
Do you happen to have the specification document handy? I'd like to implement the protocol in Go

**Comment by pavloniym** [comment]
> Do you happen to have the specification document handy? I'd like to implement the protocol in Go

Hello!
Did you find specification document?

**Comment by Alkass** [comment]
Yes, I reached out to Ruptela and had them email me a copy of their protocol specification

**Comment by VectroGPS** [comment]
Hello. Could you please share the documentation. I need to implement a trace 5

**Comment by Alkass** [comment]
@VectroGPS 
My team had to sign an NDA prior to receiving the protocol specification document, though I don't quite remember if it included keeping the document private. It's best that you reach out to Ruptela directly and ask for a copy of the document yourself.
